### ISSUE TITLE
I also can't get the ex search to work

### ISSUE THREAD

**Issue by daveguffman** [meitar/fetlife-aslsearch#10]
I can't get it to work on Chrome because it tells me it is a greasemonkey script...

**Comment by meitar** [comment]
Have you tried [actually reading and following the instructions for your browser](https://github.com/meitar/fetlife-aslsearch#google-chrome)?

**Comment by daveguffman** [comment]
I should also mention I'm on a brand new mac book osx yosemite 2.7 GHz yada yada both firefox and chrome are the latest versions.

**Comment by daveguffman** [comment]
I am following the instructions they are very simple so they are easy to follow. However I'm have the same issues as others have mentioned here.

**Comment by daveguffman** [comment]
as in, yes I have tampermonkey running on chrome...

**Comment by daveguffman** [comment]
The script says it is running on chrome, but the A/S/L check box does not appear anywhere. At least that appears on firefox...

**Comment by Numberphile** [comment]
If it's the same bug I was having... try this link:

https://script.google.com/macros/s/AKfycbxjpuCSz9uam23hztGYyiE6IbHX22EGzhq7fN4jQGo1jiRp520/exec?embedded=true
