### ISSUE TITLE
Hey fuckhead your script doesn't work try actually helping.

### ISSUE THREAD

**Issue by daveguffman** [meitar/fetlife-aslsearch#12]
Maybe don't just close issue threads without talking to people who are starting them and that will mean the program is fine and its user error. I've read your instructions, I have the grease monkey on firefox, and tampermonkey on chrome running - I have the scripts running - on firefox the A/S/L search check box is there, but it simply doesn't work the ex. search is a blank box and the classic search doesn't return results (and yes I've tried all sorts of searches - it won't return a search of everyone in the state, nor will it return a search of 35 year old female furry's or anything inbetween - no results are ever found.

On chorme there is just nothing, even though it says the script is running there is no search check box even. 

I am running the newest versions of everything. I even pulled out my old laptop and turned it on and tried the scripts and no shit I got the same exact results.

And holy shit I get it - it works fine on your machine! That must mean its flawless so I'm the fuckhead! Or maybe you could just look into it anyway because it looks like you've closed several threads of similar complaints without resolving any of them.

**Comment by meitar** [comment]
Calling me a fuckhead is a great way to ensure I help you with your issue. :)

**Comment by daveguffman** [comment]
You've already made it clear you won't help. Fuckhead.

**Comment by meitar** [comment]
> You've already made it clear you won't help. Fuckhead.

Oh, I'm happy to help folks out; [I've been doing so elsewhere](https://github.com/meitar/fetlife-aslsearch/issues/9) for people who behave respectfully and intelligently. You might also have noticed that this software was available to you at no cost, though if you feel dissatisfied I'd be very happy to refund you the full $0 you spent on it.

Here's what you're apparently still to much of an idiot to understand, Dave: I'm not happy to help *you*, specifically. As far as I'm concerned, *you*, specifically, @daveguffman , you entitled piece of shit, can go kill yourself.

Have a nice rest of your hopefully short life. :)

**Comment by daveguffman** [comment]
Get pissed off guy. Get really really pissed. That is such a fuckhead thing to do. Bye:)
