### ISSUE TITLE
unsafeWindow is not defined (Chrome)

### ISSUE THREAD

**Issue by atwellpub** [meitar/fetlife-aslsearch#14]
I've been building a JS/CSS script loader for chrome (I started a while back before I knew about Grease Monkey or Tamper Monkey) and I'm running tests on it using your script, but running into the above error message. 

I'm not positive, but I think it might be because I'm not using tamper monkey. 

Here's some data I pulled up on the issue:
http://stackoverflow.com/questions/11093759/why-isnt-chrome-unsafewindow-trick-supporting-xmlhttprequest-send-override

Please let me know if I can help in any way. 

Here's the full error message:
http://screencast.com/t/jtUIWud7Z

**Comment by meitar** [comment]
I can't view that screencast.

I also don't know how well this script will work if you're not using Tampermonkey on Google Chrome or Greasemonkey on Firefox. Those are the only two supported configurations.

If you have a patch that improves compatibility with other browsers or userscript managers, please submit that as a pull request. Thanks.
