### ISSUE TITLE
Text "report a consent violation for..." appears next to every name

### ISSUE THREAD

**Issue by adarklake** [meitar/fetlife-aslsearch#15]
After installing the script, the text "Text "report a consent violation for..." appears next to every name on the screen.  I am attaching a screen shot to show what I mean.   How do I fix this?
![sceenshot](https://cloud.githubusercontent.com/assets/13500791/8891139/eb19a7cc-32ea-11e5-9eca-ff5082ff5e50.JPG)

**Comment by meitar** [comment]
This is expected behavior.

**Comment by ImBrianHello** [comment]
Go into the script and delete everything related to "FAADE". It is the author's predator tool script that is included with this searching script. Be sure to look into what you download and install. Past reviews about this script show details about the author's character. Unfortunately, the only other search script I know of isn't safe against FetLife's banning stuff.

**Comment by ImBrianHello** [comment]
The author deleted my comment. Sad. To OP: delete everything in the script related to "FAADE" and it will fix the problem.
