### ISSUE TITLE
Why there is not all the results

### ISSUE THREAD

**Issue by prisonier2** [meitar/fetlife-aslsearch#16]
Hello,

When I'm looking for women under 25 in France with S-type, I get 19 results ....

The old ASL gabe me dozens of results.

Thanks

**Comment by meitar** [comment]
Dupe of #7.

**Comment by ImBrianHello** [comment]
To OP: It never worked right for me either. I use the classic search.

**Comment by adarklake** [comment]
Does the classic search risk you being banned?

**Comment by meitar** [comment]
> Does the classic search risk you being banned?

Yes, but you can use the stealthiness slider to decrease the risk of that.
