### ISSUE TITLE
iframe do not load - Firefox 39.0 - OSX 10.10.4

### ISSUE THREAD

**Issue by painb** [meitar/fetlife-aslsearch#17]
Hi, the iframe with the search box do not load anymore. I had issues with Chrome (ASL field disappeared) and installed firefox/greasemonkey after reading about the current Chrome issue. 

Unfortunately the script seems broken with the latest version of Firefox as well.  

Unlike the current Chrome issue the ASL box is still there, and the "FetLife A/S/L Search (Extended Edition)" is there as well, but the iframe bellow is black without content. 

Is there an easy fix for this? :smiley_cat: 

Best regards

**Comment by Romeos69** [comment]
Hello I have question I try go on my fetlife account from this program and download file what I live there but I forget password to my account do is any option to do that on meitar? And simple way step to step how?

        Thanks
Tomash

**Comment by painb** [comment]
![skjermbilde 2015-08-10 kl 13 52 33](https://cloud.githubusercontent.com/assets/13681175/9170901/3de25e76-3f67-11e5-96a8-2781a594aa50.png)
Added a screenshot for the sake of clarity.

**Comment by meitar** [comment]
@painb What operating system/browser version combination are you using?

**Comment by painb** [comment]
OSX  Yosemite 10.10.4 (14E46), Firefox 40.0 (the problem also existed with 39.0.3)

**Comment by painb** [comment]
the debug output shows:
Load denied by X-Frame-Options: https://script.google.com/macros/s/AKfycbxjpuCSz9uam23hztGYyiE6IbHX22EGzhq7fN4jQGo1jiRp520/exec?embedded=true does not permit cross-origin framing.

**Comment by meitar** [comment]
Strange. I wonder why your Firefox is behaving differently from mine. In the mean time, you can access the search functionality in a new window or tab by directly going to the URL you posted as "Load denied" while you have the userscript installed.

**Comment by dan1979** [comment]
I'm having a similar issue; the ASL field appears and I can complete it and press Search, but then it loads and stalls out, never returning any results. Anyone else having this issue?

**Comment by hexeric** [comment]
hi! i have the exact same problem! the iframe stays black.
my specs: FF 40.0.3 on Mac OS 10.10.5, if i try it in chrome the A/S/L option on top of the page does not even show up!

**Comment by meitar** [comment]
This is evidently a CORS feature that's intended to work this way so I changed the script behavior to load the Extended Search form in a new tab.

**Comment by hexeric** [comment]
hmm. this what it says for me in the new tab/window:

The proxy server is refusing connections

Firefox is configured to use a proxy server that is refusing connections.

    Check the proxy settings to make sure that they are correct.
    Contact your network administrator to make sure the proxy server is working.
