### ISSUE TITLE
Brilliant. Thank you!

### ISSUE THREAD

**Issue by AtariBaby** [meitar/fetlife-aslsearch#2]
Hi

Thank you for this! I have a couple of questions:

Is it possible to search location other than my own? I am looking for a friend I lost touch with in UK/Wales
Is it possible to sort by join date, or recent activity, or is it already sorted that way?
Is it possible to make it so that clicking on a profile opens in a new page or new tab? Currently if you click on one directly, and you try to go back, the search is wiped out.
Is there a donation button somewhere?

**Comment by meitar** [comment]
Hi,

Thanks. To answer your questions:

1. You can *filter* but not *change* the location results from the search interface. To change your search location, you will (for now) need to temporarily change your profile location to the location you want to search.
1. The search results are sorted exactly as FetLife provides them, which *I think* is join date, but it's not possible to change that sort order for the results right now.
1. Yes! Usually opening the link in a new tab is as simple is right-clicking (or command-clicking) on a link, but it also depends a bit on your web browser preferences. This is a Web browser-specific feature but it is usually enabled by default.

There's no donation *button* but there is a [donation link](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=HL954HP2N8GQY). <-- Click that if you want to donate. (I've just copied and pasted the link here. :)

Hope this helps. :)
