### ISSUE TITLE
In Chrome, "asl checkbox flashes for a second and then disappears" still happens in version 0.4.5

### ISSUE THREAD

**Issue by bgood66** [meitar/fetlife-aslsearch#29]
Hello on google chrome on el capitan asl continue to flash

**Comment by meitar** [comment]
See also #27.

Seems Chrome/Tampermonkey sandboxes the `window` object differently than Firefox.

Ah well. Maybe if you people donated more money I might spend more of my time writing code that you liked. ¯\_(ツ)_/¯

**Comment by bgood66** [comment]
Hello i have no problem to buy it if it work

**Comment by meitar** [comment]
> i have no problem to buy it if it work 

Nah, that's not how this works. This isn't a product. You're not buying anything. You would be *donating* and I feel like spending my time paying attention to this code, then I work on improving it. The more people donate, the more I "feel like" paying attention to this code, instead of [my many, many, many other projects](https://github.com/meitar/?tab=repositories) (scroll down) that I currently feel better about.

**Comment by bgood66** [comment]
I understand but I have never been able to use I discovered this script. I would make a donation when I could use . Good luck for your work and your other script

**Comment by meitar** [comment]
> I have never been able to use I discovered this script.

Try Firefox. Works in that browser, as per this issue's description.

**Comment by bgood66** [comment]
same problem on firefox

**Comment by meitar** [comment]
> same problem on firefox 

Not on mine. Can't fix something that can't be reproduced.

**Comment by bgood66** [comment]
au début il disparait et revient ensuite. merci je vais te faire un don dans la semaine

**Comment by bgood66** [comment]
i have make a donation ^^ but the search show nothing

**Comment by meitar** [comment]
> i have make a donation

Thanks for your generosity.

> the search show nothing 

Consider filing a bug report. ;) [Here's a detailed explanation of what a good bug report might contain](http://noverse.com/blog/2012/06/how-to-write-a-good-bug-report/).

**Comment by kinkystoner666** [comment]
ASL Search still not working, anyone know what's wrong with it?

**Comment by meitar** [comment]
Should be fixed in version 0.4.6 as of c16c96f2c8a2acb45c4f35756a49a2e55d129b39.
