### ISSUE TITLE
No results display, Console shows a message: 20:18:13.384 uncaught exception: NetworkError: Connection failure due to HTTP 01 <unknown>

### ISSUE THREAD

**Issue by emory** [meitar/fetlife-aslsearch#30]
20:18:13.384 uncaught exception: NetworkError: Connection failure due to HTTP 01 <unknown>

**Comment by Ornias1993** [comment]
@meitar @emory As I have no way of reproducing it and this could have about a milion sources most of which not code related: can be removed.
Also: not present in last test and code review.

**Comment by meitar** [comment]
Thanks, @Ornias1993.
