### ISSUE TITLE
Screen Frozen

### ISSUE THREAD

**Issue by Anderson-David-1981** [meitar/fetlife-aslsearch#33]
The search screen is frozen after the progress bar finishes - no results and just stays blank if I close the dialogue or click on "maybe later"
![error](https://cloud.githubusercontent.com/assets/22463757/18859791/67d17338-8445-11e6-8afb-3614b44d000b.jpg)

**Comment by forkenbrock** [comment]
I have this same issue.  The tool does not work in Firefox or Chrome.

**Comment by Anderson-David-1981** [comment]
Is it available for Internet Explorer or another browser?

**Comment by Anderson-David-1981** [comment]
Where DOES the tool work, if at all, please?

**Comment by EvilGamerX** [comment]
I can confirm that this is still a thing if anyone is actually still working on this project.

**Comment by meitar** [comment]
Duplicate of #18.
