### ISSUE TITLE
Extended A/S/L search doesn't work

### ISSUE THREAD

**Issue by RebelAries** [meitar/fetlife-aslsearch#36]
When I go to the Extended A/S/L search I have to click on an external link. When I go there and type in the parameters for the search and then hit "search" the bar fills up after about 30 seconds and I have an option to "donate via PayPal" "donate BitCoin" "other donation options" and "maybe later"... when I hit "maybe later" everything disappears. What am I doing wrong?

**Comment by meitar** [comment]
Duplicate of #18.
