### ISSUE TITLE
Extended edition not working well if at all.

### ISSUE THREAD

**Issue by ImBrianHello** [meitar/fetlife-aslsearch#4]
The classic is working fully, but the extended isn't. I'm using Google Chrome. When clicking "Open Extended A/S/L Search", it takes me to a new tab with the Google script/macro. I tried some basic searches: only 5 total entries showed up. Sometimes none show up. Sometimes it keeps loading and loading after the loading bar finishes. I even tried selecting all of the sex and role options. Help please.

Some suggestions please:
It would be helpful to have the Google script remember what I've selected or else implement a 'Select All' option for sexes and roles.
Another helpful bit would be having the option to select from a drop down list: Country>State>City. So, selecting United States(for example)will further load a drop down list of all the states, then selecting a state will load a drop down list of all the cities in that state. Or else having the option to manually add cities. So, maybe clicking a + sign to store a city's name in a drop down list or check box to be able to click on it without having to type it in. I tried doing this with the classic version in the past, but I ultimately didn't have the programming knowledge.

Thank you for reading and thank you for making this.

**Comment by meitar** [comment]
To select all options in a given panel, deselect all inputs in that panel. I.e., selecting zero genders is the same as searching for all genders.

When searches only return a few results, it's possible there aren't many results to return or it's possible that results have been batched. Click the "Show batch number 2" button to request the next batch. This is explained in the readme:

> Due to the sheer number of profiles FetLife A/S/L Search (Extended) is able to search and the speed with which it can do so, results are both batched and paged. If your search query returns many results, you will see a pagination control at the bottom of the search results table that will allow you to page through the batch. You can also filter the batch using the "Filter results batch" text field at the top-right of the table. After the first result batch is presented to you, the "Search" button becomes a "Show batch number 2" button. Clicking on it again requests the second batch from your search.
> 
> To start a new search, click the "Reset" button.
