### ISSUE TITLE
Fetlife design update

### ISSUE THREAD

**Issue by deanpr** [meitar/fetlife-aslsearch#46]
Classic search is still working however due Fetlife's design update in the last couple of weeks the placement of the ASL-search container is now all on the right. I tried to move things myself but I'm not experienced enough. Would be awesome if changes to the layout could be made so the classic search is still usable in the future.

**Comment by Readywhenyouare** [comment]
Sorry, I can't help you there but I understand the extended search isn't currently working?

**Comment by geoffbrooks90** [comment]
Correct. In Chrome, after you click <Search>, it just says "Loading" and doesn't change (I waited for about half an hour). In Firefox, the ASL checkbox doesn't show at all.

**Comment by Readywhenyouare** [comment]
Yes that's the only thing is does, but it's broken. Too bad because searching profiles is a real pain in the ass.

I've donated E 50,- months ago and send de programmer a email but not even got 1 word back.

**Comment by deanpr** [comment]
No the classic search was actually still working till a few days ago (only with a lot of layout issues, but it  was returning results). Now it does not give any results at all, keeps searching...... Seems like due changes the script is not able to connect to the database anymore. Would be awesome if you could do an update @meitar.
