### ISSUE TITLE
Can't update location

### ISSUE THREAD

**Issue by Slofe** [meitar/fetlife-aslsearch#48]
Hello,

This script is a little wonky but generally works well.  I can't seem to update the location it searches in though as the 'Update Location' button doesn't do anything when I click on it.  Is there a way I could update my location manually? Thanks.

**Comment by meitar** [comment]
Read [the FAQ](https://github.com/meitar/fetlife-aslsearch/blob/master/README.markdown#can-i-search-in-a-location-other-than-my-own-city-state-or-country).

**Comment by Slofe** [comment]
I was talking about the classic edition but seems you couldn't choose a location anyway. The extended search doesn't work at all anymore and hasn't for some time.

**Comment by meitar** [comment]
> I was talking about the classic edition

So was I.

**Comment by Slofe** [comment]
OK, either way it doesn't work. I can't actually type anything in because when I click on the location to change it nothing happens.
