### ISSUE TITLE
Extended edition results not displaying all results.

### ISSUE THREAD

**Issue by ImBrianHello** [meitar/fetlife-aslsearch#7]
Total number of entries significantly less than the classic search.
179 in the first batch, only 5 in the second batch  - versus - hundreds more in the classic search, not including the inactive profiles the extended search does.

**Comment by meitar** [comment]
The Extended search queries a constantly updating cache of results. It's always at least several hours behind live results but it gets there.

**Comment by ImBrianHello** [comment]
I don't really understand please. Am I to wait hours after the first batch loads then reset and search again?

**Comment by meitar** [comment]
No. Let me put this another way: if the Extended Search isn't showing you many up-to-date results, feel free to do the same search using the Classic search method. After you do that, in a few hours tops but probably sooner, the Extended Search will have been auto-updated to include the same results from the Classic method.

**Comment by ImBrianHello** [comment]
Thanks for responding. I will try that. Will the results be ascending from page 1 of a city like in the classic?

**Comment by meitar** [comment]
No, the results are only sorted within a single batch. You can sort the results within the batch by any column (ascending or descending) by clicking on the result's column header. For example, to sort by youngest to oldest, click the top of the Age column.
